language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t jaeha23/docker-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true jaeha23/docker-test-app npm test

after_success:
  - docker build -t jaeha23/docker-frontend ./frontend
  - docker build -t jaeha23/docker-backend ./backend
  - docker build -t jaeha23/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push jaeha23/docker-frontend
  - docker push jaeha23/docker-backend
  - docker push jaeha23/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-test-app"
  env: "Dockertestapp-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-638665892116
  bucket_path: "docker-test-app"
  on:
    branch: main

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
